version: "3.8"
services:
  app:
    build: .
    container_name: streamlit_fastapi_app
    ports:
      - "8501:8501"   # Port Streamlit
      - "8000:8000"   # Port FastAPI
    volumes:
      - .:/app
    environment:
      # Exemple de variables d'environnement (facultatif)
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
